# Generated by Django 5.0.6 on 2024-05-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='desc',
            new_name='content',
        ),
    ]
