# Generated by Django 5.0.6 on 2024-05-27 06:10

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(unique=True)),
                ('desc', models.TextField(max_length=500)),
                ('limithour', models.PositiveSmallIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', related_query_name='exam', to='groups.subject')),
            ],
            options={
                'unique_together': {('ordering', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precent', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(max_length=300)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results', related_query_name='exam_results', to='tasks.exam')),
                ('student', models.ForeignKey(limit_choices_to={'status': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_results', related_query_name='student_exam_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('desc', django_ckeditor_5.fields.CKEditor5Field()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.subject')),
            ],
            options={
                'unique_together': {('ordering', 'subject')},
            },
        ),
    ]
