# Generated by Django 5.0.6 on 2024-05-25 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(unique=True)),
                ('desc', models.TextField(max_length=500)),
                ('month', models.IntegerField()),
                ('limithour', models.PositiveSmallIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', related_query_name='exam', to='groups.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precent', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(max_length=300)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_result', related_query_name='exam_result', to='tasks.exam')),
                ('student', models.ForeignKey(limit_choices_to={'status': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_result', related_query_name='student_exam_result', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
