# Generated by Django 5.0.6 on 2024-05-23 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(limit_choices_to={'status': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_result', related_query_name='student_exam_result', to=settings.AUTH_USER_MODEL),
        ),
    ]
