# Generated by Django 5.0.6 on 2024-05-27 07:15

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_lesson_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='comment',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
