# Generated by Django 5.0.6 on 2024-05-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField()),
                ('sender_phone_number', models.CharField()),
                ('sender_fullname', models.CharField()),
                ('recipient_phone_number', models.CharField()),
                ('recipient_fullname', models.CharField()),
                ('title', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=255)),
                ('viwed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.PositiveSmallIntegerField(choices=[(0, 'EXAM_RESULT'), (1, 'ON_ATTENDANCE'), (2, 'STUDENT_PAYMENT'), (3, 'SELARY'), (4, 'ACCOUNT'), (5, 'FINE'), (6, 'WARNING')])),
                ('is_viewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
