# Generated by Django 5.0.6 on 2024-05-29 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'status': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_groups', related_query_name='teacher_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
