# Generated by Django 5.0.6 on 2024-05-25 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(limit_choices_to={'status': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendence', related_query_name='student_attendence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'status': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='group', related_query_name='group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendence',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', related_query_name='attendence', to='groups.studentgroup'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group', related_query_name='group', to='groups.subject'),
        ),
    ]
