# Generated by Django 5.0.6 on 2024-05-23 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 23, 10, 56, 5, 39122, tzinfo=datetime.timezone.utc)),
        ),
    ]
