# Generated by Django 5.0.6 on 2024-05-23 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'status': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_payment', related_query_name='student_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'status': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_payment', related_query_name='teacher_payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('year', 'month', 'student', 'teacher')},
        ),
    ]
