# Generated by Django 5.0.6 on 2024-05-28 09:02

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('name_uz', models.CharField(max_length=70, null=True)),
                ('name_en', models.CharField(max_length=70, null=True)),
                ('name_ru', models.CharField(max_length=70, null=True)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('desc', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('price', models.DecimalField(decimal_places=2, help_text='Add in UZS', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
