# Generated by Django 5.0.6 on 2024-05-30 05:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=70)),
                ('title_uz', models.CharField(max_length=70, null=True)),
                ('title_en', models.CharField(max_length=70, null=True)),
                ('title_ru', models.CharField(max_length=70, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('desc', models.CharField(max_length=255)),
                ('desc_uz', models.CharField(max_length=255, null=True)),
                ('desc_en', models.CharField(max_length=255, null=True)),
                ('desc_ru', models.CharField(max_length=255, null=True)),
                ('limit_hour', models.PositiveSmallIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', related_query_name='exam', to='subjects.subject')),
            ],
            options={
                'unique_together': {('ordering', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precent', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results', related_query_name='exam_results', to='exams.exam')),
                ('student', models.ForeignKey(limit_choices_to={'status': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='student_exam_results', related_query_name='student_exam_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
