# Generated by Django 5.0.6 on 2024-05-28 09:02

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(unique=True)),
                ('desc', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('limit_hour', models.PositiveSmallIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', related_query_name='exam', to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precent', models.PositiveSmallIntegerField()),
                ('comment', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_results', related_query_name='exam_results', to='exams.exam')),
            ],
        ),
    ]
