# Generated by Django 5.0.6 on 2024-05-30 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('came', models.BooleanField(default=True)),
                ('date', models.DateField()),
                ('resone', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendence', related_query_name='attendence', to='groups.studentgroup')),
                ('student', models.ForeignKey(limit_choices_to={'status': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendence', related_query_name='student_attendence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
