# Generated by Django 5.0.6 on 2024-05-28 09:02

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('desc', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'unique_together': {('ordering', 'subject')},
            },
        ),
    ]
