# Generated by Django 5.0.6 on 2024-05-30 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('title_uz', models.CharField(max_length=70, null=True)),
                ('title_en', models.CharField(max_length=70, null=True)),
                ('title_ru', models.CharField(max_length=70, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('desc', models.CharField(max_length=255)),
                ('desc_uz', models.CharField(max_length=255, null=True)),
                ('desc_en', models.CharField(max_length=255, null=True)),
                ('desc_ru', models.CharField(max_length=255, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', related_query_name='tasks', to='subjects.subject')),
            ],
        ),
    ]
